### ISSUE TITLE
Use infinite loop instead of set number of epochs

### ISSUE THREAD

**Issue by dberenbaum** [iterative/dvc-checkpoints-mnist#13]
Having a set number of epochs in the training is not the most likely workflow for checkpoints, and it may be confusing since it implies an expected number of epochs. See https://discuss.dvc.org/t/experiments-with-checkpoint/744.

I was concerned that users might not read about interrupting the script and be waiting endlessly for the experiment to end, but @pmrowla suggested how this could be pretty easily avoided:

> we could make the example stage an infinite loop, and just have the stage code print a help message on the command line like “running forever… press ctrl-c to exit” in case they miss the relevant line in the docs themselves

**Comment by shcheklein** [comment]
cc @iesahin - do the same for the new repo?

**Comment by iesahin** [comment]
In the new repository, `epochs` is a parameter in `params.yaml`. `dvc exp run -S train.epochs=100` runs it for 100 epochs and saves a checkpoint after each epoch, e.g., [when using `python-api`.](https://github.com/iterative/dvc-get-started/blob/python-api/src/train.py#L103) 

@shcheklein @dberenbaum

**Comment by iesahin** [comment]
I can also have an `infinite-training` example with one of the checkpoints' tags to show `Ctrl-C` usage. Or rather `indefinite-training` :)

**Comment by dberenbaum** [comment]
For checkpoints, indefinite-training might be best.

**Comment by casperdcl** [comment]
Considering that the aim is to act as a good reference, I think better would be to fix resuming. Right now, `dvc exp run && dvc exp run` will do 20 epochs rather than just 10 (related https://github.com/iterative/dvc/issues/6183) because the user code in this repo doesn't check the epoch number from the workspace state

**Comment by dberenbaum** [comment]
> Right now, `dvc exp run && dvc exp run` will do 20 epochs rather than just 10 (related [iterative/dvc#6183](https://github.com/iterative/dvc/issues/6183))

This was intended. Whether that's desirable depends on the use case:

1. Tracking training epochs to tune hyperparameters, including the optimal number of epochs.
2. Recovering from failures in the middle of a training stage.

The existing docs and examples for checkpoints were intended for the first scenario, and users were expected to keep running them for more than 10 epochs to keep optimizing performance. It still seems like the first scenario is the most useful starting point, since recovering from failures is less of a problem when running locally (I think you could just set `persist: true` and not use checkpoints at all to recover from a local failure).

It would be helpful to also have an example that stops after a set number of checkpoints and works for recovering from failures, and I opened https://github.com/iterative/dvc.org/issues/2568 to track that.

**Comment by daavoo** [comment]
> The existing docs and examples for checkpoints were intended for the first scenario, and users were expected to keep running them for more than 10 epochs to keep optimizing performance. I

I think that, in addition to  iterative/dvc.org#2568, we should better clarify this default behavior in the docs. 

We are just using the term "resume training" which, as @casperdcl pointed out, doesn't match people's expectations. In  most *ML Frameworks* "resume training" means that you will train for `{n_epochs} - {resuming_epoch}`

**Comment by casperdcl** [comment]
related: https://github.com/iterative/dvclive/pull/142
